name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Gen ChangeList
        run: ./scripts/changelist.sh
      - name: Create Release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: ./scripts/header.md
          draft: false
          prerelease: false

  build:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    needs:
      - release
    strategy:
      fail-fast: true
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            rename: windows_x86_64
          - target: x86_64-unknown-linux-musl
            rename: linux-x86_64
          - target: x86_64-apple-darwin
            rename: darwin_x86_64
    steps:
      - name: Checkout Code
        uses: actions/checkout@master
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "(.*)"
      - name: build and publish
        run: |
          ./scripts/release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          RENAME: ${{matrix.rename}}
